language: php

php:
  - "5.3"
  - "5.4"

before_script:
  - composer install
  - pear config-set auto_discover 1
  - pear install pear.phpqatools.org/phpqatools
  - phpenv rehash

script:
  - ant ci

notifications:
  email:
    - travis-ci@yuriteixeira.com.br